### ISSUE TITLE
xx_id or simply xx? 

### ISSUE THREAD

**Issue by RobertPincus** [eurec4a/meta#20]
In the [guidance on meta-data](https://github.com/eurec4a/meta/blob/master/naming_conventions.md) (which perhaps confusingly still includes much discussion of file names) all parameters have the suffix `_id`. Is this necessary, or would it be simpler to adopt meta-data attributes such as `campaign`, `activity`, etc?

**Comment by d70-t** [comment]
I think that was a result of the discussion to emphasize that all of these items should be identifiers for which we must take care that they are spelled in a unique way. But yes, the `_id` suffix is not really needed and if we follow the [rules of clean code on naming things](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29#names-rules), we should

> Avoid encodings. Don't append prefixes or type information.

And as I would argue that `id` is kind of a type information, we should get rid of it.
